### ISSUE TITLE
Exception in thread "main" java.net.SocketTimeoutException: Connect timed out

### ISSUE THREAD

**Issue by sitoc** [freeok/so-novel#31]
按 Tab 键选择功能: 1.下载小说
==> 请输入书名或作者: 明朝那些事儿
<== 正在搜索...
Exception in thread "main" java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:861)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:831)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:351)
        at org.jsoup.helper.HttpConnection.post(HttpConnection.java:344)
        at com.pcdd.sonovel.parse.SearchResultParser.parse(SearchResultParser.java:30)
        at com.pcdd.sonovel.core.Crawler.search(Crawler.java:73)
        at com.pcdd.sonovel.action.DownloadAction.execute(DownloadAction.java:26)
        at com.pcdd.sonovel.Main.main(Main.java:50)
+－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－+

**Comment by freeok** [comment]
![image](https://github.com/user-attachments/assets/58eba088-1f56-4549-9d96-f71e277b69ce)
