### ISSUE TITLE
epub打不开提示损坏，合并txt报错

### ISSUE THREAD

**Issue by WallenSnow** [freeok/so-novel#38]
RT，epub能够成功合成，但是无法打开，提示已损坏；
txt无法合成，报错如下：
Exception in thread "main" cn.hutool.core.io.IORuntimeException: IOException: 文件名、目录名或卷标语法不正确。
        at cn.hutool.core.io.FileUtil.getParent(FileUtil.java:3504)
        at cn.hutool.core.io.FileUtil.mkParentDirs(FileUtil.java:727)
        at cn.hutool.core.io.FileUtil.touch(FileUtil.java:680)
        at cn.hutool.core.io.FileUtil.touch(FileUtil.java:664)
        at com.pcdd.sonovel.core.CrawlerPostHandler.mergeTxt(CrawlerPostHandler.java:100)
        at com.pcdd.sonovel.core.CrawlerPostHandler.handle(CrawlerPostHandler.java:54)
        at com.pcdd.sonovel.core.Crawler.crawl(Crawler.java:137)
        at com.pcdd.sonovel.action.DownloadAction.execute(DownloadAction.java:52)
        at com.pcdd.sonovel.Main.main(Main.java:50)
Caused by: java.io.IOException: 文件名、目录名或卷标语法不正确。
        at java.base/java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.base/java.io.WinNTFileSystem.canonicalize(Unknown Source)
        at java.base/java.io.File.getCanonicalPath(Unknown Source)
        at java.base/java.io.File.getCanonicalFile(Unknown Source)
        at cn.hutool.core.io.FileUtil.getParent(FileUtil.java:3502)
        ... 8 more

**Comment by freeok** [comment]
os、config.ini？

**Comment by freeok** [comment]
你修改默认下载位置了吧？检查路径分隔符

**Comment by WallenSnow** [comment]
> os、config.ini？

Windows 

config：
# 下载路径，绝对相对均可
# Windows 路径分隔符不要用 \ ，用 \\ 或 /
savePath=C:\\Users\\burto\\Downloads

# 文件扩展名，支持 txt、html、epub，推荐 epub
extName=html  # txt和epub都尝试过无法成功
# 爬取最小间隔 (ms)
min=1

# 爬取最大间隔 (ms)
max=10

# 爬取线程数，-1 表示自动设置
threads=-1

# 下载失败章节最大重试次数
retryCount=10

# 重试爬取最小间隔 (ms)
retryMin=100

# 重试最大间隔 (ms)
retryMax=3000

**Comment by WallenSnow** [comment]
> 你修改默认下载位置了吧？检查路径分隔符

Windows，在默认下载位置也出现这个问题了~提示损坏；其他config没有动

**Comment by freeok** [comment]
epub提示已损坏：用的什么阅读器？
txt无法合成：可以截下图吗？config.ini和exe所在的目录结构

**Comment by freeok** [comment]
试下最新预览版有这个问题没：https://github.com/freeok/so-novel/releases/tag/v1.7.0

**Comment by WallenSnow** [comment]
> epub提示已损坏：用的什么阅读器？ txt无法合成：可以截下图吗？config.ini和exe所在的目录结构
下载1.7.0beta版本后txt问题已解决，可正常合成；

epub损坏使用的是wps打开；正常wps是可以打开epub的。

目录结构和报错如图所示，解压后除config里的txt格式外没有进行任何修改。

![微信图片_20241129001700](https://github.com/user-attachments/assets/795f9b4b-aaa2-4215-8df6-dd6514b4d648)
![微信图片_20241129001658](https://github.com/user-attachments/assets/a97bb8af-9406-427b-acb7-fb190b466c2d)
![微信图片_20241129001655](https://github.com/user-attachments/assets/64a45ebb-4377-405a-98cd-ee54021eafc3)
![微信图片_20241129001650](https://github.com/user-attachments/assets/87b039ae-90d7-4344-9e68-67734cee6191)

**Comment by WallenSnow** [comment]
> epub提示已损坏：用的什么阅读器？ txt无法合成：可以截下图吗？config.ini和exe所在的目录结构
下载1.7.0beta版本后txt问题已解决，可正常合成；

epub损坏使用的是wps打开；正常wps是可以打开epub的。

目录结构和报错如图所示，解压后除config里的txt格式外没有进行任何修改。

![微信图片_20241129001700](https://github.com/user-attachments/assets/795f9b4b-aaa2-4215-8df6-dd6514b4d648)
![微信图片_20241129001658](https://github.com/user-attachments/assets/a97bb8af-9406-427b-acb7-fb190b466c2d)
![微信图片_20241129001655](https://github.com/user-attachments/assets/64a45ebb-4377-405a-98cd-ee54021eafc3)
![微信图片_20241129001650](https://github.com/user-attachments/assets/87b039ae-90d7-4344-9e68-67734cee6191)

**Comment by freeok** [comment]
https://github.com/freeok/so-novel/issues/32 
windows 端推荐使用 [koodo-reader](https://github.com/koodo-reader/koodo-reader) 阅读器
目前可以确定的是用 apple books、koodo-reader、kindle 等主流阅读器都可以打开生成的 epub
后面再排查下
